
on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 55bed88fa1eca03d8e9cea17307325828b57bfcd

    - name: Build C Code
      run: |
        find . -name '*.c' -print0 | xargs -0 -I {} clang++ -fsanitize=undefined -o {}.out {}
