
name: Build

on:
  push:

jobs:
  build-for-linux:
    name: Linux GCC
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: ./build_duet.tool
        run: docker compose run build-duet

      - name: ./build_oc.tool
        run: docker compose run build-oc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux GCC Artifacts
          path: Binaries/*.zip
